from datetime import datetime

from pydantic import BaseModel, Field

from app.core.enums import TASK_TYPE, TASK_STATUS


class AddTask(BaseModel):
    identifier: str = Field(
        description="Unique identified of the task. If not passed then its autogenerated using payload-hash")
    task_type: TASK_TYPE = Field(description="Describes what kind of task needs to be done. Eg - SEND_EMAIL")
    payload: str | None = Field(default=None,
                                description="Default payload, mostly in json, need for the task to do processing")
    attempts: int | None = Field(default=None, description="Number of attempts for this job", gt=0, lt=5)
    max_attempts: int | None = Field(default=None, description="Maximum number of attempts for this job", gt=1, lt=5)
    priority: str | None = Field(default=None, description="Priority of task. Default is MEDIUM")
    run_at: datetime | None = Field(default=None, description="After what datetime should the task start")


class updateTask(BaseModel):
    max_attempts: int | None = Field(default=None, description="Maximum number of attempts for this job", gt=1, lt=5)
    status: TASK_STATUS | None = Field(default=None, description="Describes the last status")
    error_msg: str | None = Field(default=None, description="Describes the error occurred during last processing")
    run_at: datetime | None = Field(default=None, description="Describes the datetime when the task processing begins")
